# Generated by Django 5.2.7 on 2025-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('nationalite', models.CharField(default='Malagasy', max_length=100)),
                ('situation_familiale', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve'), ('U', 'Union libre')], default='C', max_length=1)),
                ('numero_cin', models.CharField(max_length=20, unique=True)),
                ('numero_passeport', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_contribuable', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('employeur', models.CharField(blank=True, max_length=100, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('situation_professionnelle', models.CharField(choices=[('A', 'Actif'), ('C', 'Chômeur'), ('E', 'Étudiant'), ('R', 'Retraité'), ('I', 'Indépendant'), ('F', 'Fonctionnaire')], default='A', max_length=1)),
                ('revenu_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('niveau_education', models.CharField(blank=True, choices=[('P', 'Primaire'), ('S', 'Secondaire'), ('B', 'Baccalauréat'), ('U', 'Universitaire'), ('M', 'Master'), ('D', 'Doctorat')], max_length=1, null=True)),
                ('diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=200, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('couverture_medicale', models.BooleanField(default=False)),
                ('nom_medecin_traitant', models.CharField(blank=True, max_length=100, null=True)),
                ('bureau_vote', models.CharField(blank=True, max_length=100, null=True)),
                ('circonscription_electorale', models.CharField(blank=True, max_length=100, null=True)),
                ('situation_militaire', models.CharField(blank=True, max_length=100, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_citoyens/')),
                ('empreinte_digitale', models.BinaryField(blank=True, null=True)),
                ('nom_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_mere', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'ordering': ['nom', 'prenoms'],
                'indexes': [models.Index(fields=['numero_cin'], name='population__numero__636321_idx'), models.Index(fields=['nom', 'prenoms'], name='population__nom_8f4a12_idx'), models.Index(fields=['province', 'commune'], name='population__provinc_def072_idx')],
            },
        ),
    ]
