# Generated by Django 5.2.7 on 2025-10-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='numero_cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
